import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire
import 'screens/conductor_login_page.dart'; // your main app screen
import 'services/app_config.dart';

Future<void> main() async {
  await AppConfig.initialize();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: ConductorLoginPage(),
  ));
}
